### ISSUE TITLE
issue name version

### ISSUE THREAD

**Issue by 3xploiton3** [nklido/qBittorrent_search_engines#3]
![image](https://user-images.githubusercontent.com/19517680/179538351-ebe0ebea-700d-4675-8588-c410056be661.png)

**Comment by nklido** [comment]
Thanks for the report

fixed in [1bba5d3](https://github.com/nklido/qBittorrent_search_engines/commit/1bba5d37edc74ea083fb096f9bfb2a55a7181265)
