### ISSUE TITLE
[BUG] AudioBook Bay (ABB) is not precise

### ISSUE THREAD

**Issue by Pocokk** [nklido/qBittorrent_search_engines#6]
Hello,

Script version: latest 0.0.1
Qbittorrent version: v4.6.2 64-bit

Issue: When I search for a name, AudioBook Bay lists a bunch of unrelated results, see the picture below.

Can it be "smarten up" a little ?

![audiobookbay](https://github.com/nklido/qBittorrent_search_engines/assets/81096046/2258cb2d-532e-436c-8e6d-6a0485dc2d6d)

**Comment by nklido** [comment]
Hey there @Pocokk,

Good catch! I just checked out the example on the AudioBookBay [website](https://audiobookbay.is/?s=blade+joker+and+clowns&cat=undefined%2Cundefined), and you're right. It seems to throw in some random results when there's nothing to show. I'll dig into it when I've got a moment.

Cheers!

**Comment by Pocokk** [comment]
Appreciate the reply, patiently waiting!

**Comment by Pocokk** [comment]
Well, something amiss: when I try to install it, it freezes qbittorrent for like 10 seconds and then at the end gives an error message, saying plugin is not supported

https://i.imgur.com/EjLKZ1X.png

**Comment by nklido** [comment]
@Pocokk Did you uninstall it first? Also what version of qBittorrent do you use?

For me it works find on windows with qBittorrent v4.6.3 (64-bit) and python 3.12.1.

I used this [link](https://raw.githubusercontent.com/nklido/qBittorrent_search_engines/master/engines/audiobookbay.py) to install.

**Comment by Pocokk** [comment]
Yes I did, first uninstalled, then tried to implement it as any other script previously.

4.6.2 64-bit and python 3.11 are my versions, let me upgrade it to 4.6.3 and check again

Edit: it worked! 

somehow I redownloaded it using Your given link and its fine now, thank you!
